### ISSUE TITLE
Place the example folder in another repo

### ISSUE THREAD

**Issue by kaiomagalhaes** [marcelobarreto/autocomplete_zipcode#1]
It is a really bad practice to have a project inside another. It messes up with the git history.

**Comment by marcelobarreto** [comment]
@kaiomagalhaes Thanks for this issue, I'll fix this as soon as possible, really thanks :heart:

**Comment by kaiomagalhaes** [comment]
@marcelobarreto you're welcome. It seems to be a very useful gem. Will use it as soon as the chance appears.
